### ISSUE TITLE
Problem with administrative session / AEM 6.3

### ISSUE THREAD

**Issue by pun-ky** [wttech/CQ-Actions#16]
https://github.com/Cognifide/APM/issues/78#issuecomment-317404128

**Comment by mierzwid** [comment]
Not surprisingly, this problem is also present on AEM 6.4. Please add at least information to the README that one needs to whitelist cqactions to make them work at all:
/apps/training/config/org.apache.sling.jcr.base.internal.LoginAdminWhitelist.fragment-cqactions.xml
```<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"
    jcr:primaryType="sling:OsgiConfig"
    whitelist.bundles="[com.cognifide.cq.actions.core,com.cognifide.cq.actions.msg.replication]"
    whitelist.name="cqactions"/>
```

**Comment by devzbysiu** [comment]
This project is going to be archived. Closing
